import { User, Book, BookRequest, BookAdditionRequest, Review, IssuedBook } from '../types';

export const seedData = {
  currentUser: null,
  users: [
    {
      id: 'admin-1',
      fullName: 'Library Administrator',
      dateOfBirth: '1990-01-01',
      class: '',
      studentId: 'LibAdmin',
      email: 'admin@library.com',
      password: '12qwaszx',
      role: 'admin' as const,
      coins: 0,
      joinDate: '2024-01-01',
    },
    {
      id: 'student-1',
      fullName: 'Alice Johnson',
      dateOfBirth: '2008-05-15',
      class: '10th Grade',
      studentId: 'STU001',
      email: 'alice@student.com',
      password: 'student123',
      role: 'student' as const,
      coins: 125,
      joinDate: '2024-01-15',
    },
    {
      id: 'student-2',
      fullName: 'Bob Smith',
      dateOfBirth: '2007-08-22',
      class: '11th Grade',
      studentId: 'STU002',
      email: 'bob@student.com',
      password: 'student123',
      role: 'student' as const,
      coins: 95,
      joinDate: '2024-01-20',
    },
  ] as User[],
  books: [
    {
      id: 'book-1',
      title: 'The Great Gatsby',
      author: 'F. Scott Fitzgerald',
      category: 'Fiction',
      description: 'A classic American novel set in the Jazz Age.',
      coverUrl: 'https://images.pexels.com/photos/1130980/pexels-photo-1130980.jpeg',
      totalQuantity: 5,
      availableQuantity: 3,
      rating: 4.2,
      reviews: [],
      uniqueIds: ['GG001', 'GG002', 'GG003', 'GG004', 'GG005'],
    },
    {
      id: 'book-2',
      title: 'To Kill a Mockingbird',
      author: 'Harper Lee',
      category: 'Fiction',
      description: 'A gripping tale of racial injustice and childhood innocence.',
      coverUrl: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg',
      totalQuantity: 4,
      availableQuantity: 4,
      rating: 4.8,
      reviews: [],
      uniqueIds: ['TKM001', 'TKM002', 'TKM003', 'TKM004'],
    },
    {
      id: 'book-3',
      title: 'A Brief History of Time',
      author: 'Stephen Hawking',
      category: 'Science',
      description: 'An exploration of the universe and our place in it.',
      coverUrl: 'https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg',
      totalQuantity: 3,
      availableQuantity: 2,
      rating: 4.5,
      reviews: [],
      uniqueIds: ['BHOT001', 'BHOT002', 'BHOT003'],
    },
    {
      id: 'book-4',
      title: 'The Art of War',
      author: 'Sun Tzu',
      category: 'Philosophy',
      description: 'Ancient Chinese military treatise on strategy and tactics.',
      coverUrl: 'https://images.pexels.com/photos/1907785/pexels-photo-1907785.jpeg',
      totalQuantity: 6,
      availableQuantity: 5,
      rating: 4.1,
      reviews: [],
      uniqueIds: ['AOW001', 'AOW002', 'AOW003', 'AOW004', 'AOW005', 'AOW006'],
    },
    {
      id: 'book-5',
      title: 'Steve Jobs',
      author: 'Walter Isaacson',
      category: 'Biography',
      description: 'The authorized biography of Apple co-founder Steve Jobs.',
      coverUrl: 'https://images.pexels.com/photos/694740/pexels-photo-694740.jpeg',
      totalQuantity: 2,
      availableQuantity: 1,
      rating: 4.6,
      reviews: [],
      uniqueIds: ['SJ001', 'SJ002'],
    },
    {
      id: 'book-6',
      title: 'The Hobbit',
      author: 'J.R.R. Tolkien',
      category: 'Adventure',
      description: 'A fantasy adventure about Bilbo Baggins\' unexpected journey.',
      coverUrl: 'https://images.pexels.com/photos/415188/pexels-photo-415188.jpeg',
      totalQuantity: 7,
      availableQuantity: 6,
      rating: 4.7,
      reviews: [],
      uniqueIds: ['HOB001', 'HOB002', 'HOB003', 'HOB004', 'HOB005', 'HOB006', 'HOB007'],
    },
  ] as Book[],
  bookRequests: [
    {
      id: 'req-1',
      userId: 'student-1',
      bookId: 'book-1',
      requestDate: '2024-01-25',
      status: 'pending' as const,
    },
  ] as BookRequest[],
  bookAdditionRequests: [
    {
      id: 'add-req-1',
      userId: 'student-2',
      title: 'Clean Code',
      referenceLink: 'https://example.com/clean-code',
      requestDate: '2024-01-24',
      status: 'pending' as const,
    },
  ] as BookAdditionRequest[],
  reviews: [] as Review[],
  issuedBooks: [
    {
      id: 'issued-1',
      userId: 'student-1',
      bookId: 'book-5',
      uniqueBookId: 'SJ002',
      issueDate: '2024-01-20',
      dueDate: '2024-02-05',
      penaltyCoins: 0,
    },
  ] as IssuedBook[],
};